version: '3.5'

services:
    mongo_db:
      container_name: mongo_db
      image: mongo:latest
      ports:
        - 27018:27017
    minio:
      image: minio/minio
      container_name: minio
      environment:
        - MINIO_ROOT_USER=ift_bigdata
        - MINIO_ROOT_PASSWORD=minio_password
        - MINIO_DOMAIN=minio
      ports:
        - 9001:9001
        - 9000:9000
      command: ["server", "/data", "--console-address", ":9001"]
    minio_client:
      container_name: minio_client
      depends_on:
        - minio
      image: minio/mc
      environment:
        - AWS_ACCESS_KEY_ID=ift_bigdata
        - AWS_SECRET_ACCESS_KEY=minio_password
        - AWS_REGION=us-east-1
      entrypoint: >
        /bin/bash -c "
        until (/usr/bin/mc config host add minio http://minio:9000 ift_bigdata minio_password) do echo '...waiting...' && sleep 1; done;
        sleep 10 && /usr/bin/mc rm -r --force minio/icebergwarehouse;
        sleep 10 && /usr/bin/mc mb minio/icebergwarehouse;
        mc anonymous set public minio/icebergwarehouse;
        tail -f /dev/null
        "      
    iceberg_rest:
      container_name: iceberg_rest
      image: tabulario/iceberg-rest
      ports:
        - "8181:8181"
      environment:
        - AWS_ACCESS_KEY_ID=ift_bigdata
        - AWS_SECRET_ACCESS_KEY=minio_password
        - AWS_REGION=us-east-1
        - CATALOG_S3_PATH__STYLE__ACCESS=true
        - CATALOG_WAREHOUSE=s3://icebergwarehouse/
        - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
        - CATALOG_S3_ENDPOINT=http://minio:9000
      depends_on:
        - minio
    pythonice:
      container_name: pythonice
      image: python:3.9
      working_dir: /app
      command: tail -f /dev/null
      depends_on:
        - minio
        - iceberg_rest
networks:
  proxynet:
    name: database_network
